[[plugins]]
on_ft = ['elm']
repo = 'ElmCast/elm-vim'
hook_source = '''
  let g:elm_setup_keybindings = 0
'''

[[plugins]]
on_ft = ['html']
repo = 'mattn/emmet-vim'

[[plugins]]
on_ft = ['kotlin']
repo = 'udalov/kotlin-vim'

[[plugins]]
on_ft = ['tex']
repo = 'lervag/vimtex'
hook_source = '''
  let g:vimtex_view_general_viewer = 'displayline'
  let g:vimtex_view_general_options = '@line @pdf @tex'
  let g:vimtex_quickfix_enabled = 0
'''

[[plugins]]
on_ft = ['toml']
repo = 'cespare/vim-toml'
