[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_sign_column_always = 1
  let g:ale_completion_enabled = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  highlight GitGutterAdd ctermfg=green
  highlight GitGutterChange ctermfg=yellow
  highlight GitGutterDelete ctermfg=red
'''
